#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/ChooseHome.jar:$APPDIR/lib/core.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/RXTXcomm.jar:$APPDIR/lib/old-RXTXcomm.jar:$APPDIR/lib/json4processing.jar:$APPDIR/lib/Unfolding.jar:$APPDIR/lib/log4j-1.2.15.jar:$APPDIR/lib/opengl.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl.jar:$APPDIR/lib/GLGraphics.jar:$APPDIR/lib/guicomponents.jar:$APPDIR/lib/http.jar:$APPDIR/lib/commons-codec-1.4.jar:$APPDIR/lib/httpcore-4.1.2.jar:$APPDIR/lib/signpost-commonshttp4-1.2.1.1.jar:$APPDIR/lib/signpost-core-1.2.1.1.jar:$APPDIR/lib/httpclient-4.1.2.jar:$APPDIR/lib/stringtree-json-2.0.10.jar:$APPDIR/lib/httpclient-cache-4.1.2.jar:$APPDIR/lib/commons-logging-1.1.1.jar:$APPDIR/lib/httpmime-4.1.2.jar" ChooseHome
